// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/todo.proto

package model // import "github.com/guilhermesteves/go-todo-api/internal/pkg/core/model"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ToDo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToDo) Reset()         { *m = ToDo{} }
func (m *ToDo) String() string { return proto.CompactTextString(m) }
func (*ToDo) ProtoMessage()    {}
func (*ToDo) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_913f984c26ceceb1, []int{0}
}
func (m *ToDo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToDo.Unmarshal(m, b)
}
func (m *ToDo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToDo.Marshal(b, m, deterministic)
}
func (dst *ToDo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToDo.Merge(dst, src)
}
func (m *ToDo) XXX_Size() int {
	return xxx_messageInfo_ToDo.Size(m)
}
func (m *ToDo) XXX_DiscardUnknown() {
	xxx_messageInfo_ToDo.DiscardUnknown(m)
}

var xxx_messageInfo_ToDo proto.InternalMessageInfo

func (m *ToDo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ToDo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ToDo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ToDo) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*ToDo)(nil), "ToDo")
}

func init() { proto.RegisterFile("model/todo.proto", fileDescriptor_todo_913f984c26ceceb1) }

var fileDescriptor_todo_913f984c26ceceb1 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xce, 0x31, 0xcb, 0xc2, 0x30,
	0x10, 0xc6, 0x71, 0xda, 0xb7, 0xbc, 0xd0, 0x0c, 0x22, 0x99, 0x3a, 0x38, 0x88, 0x93, 0x4b, 0x7b,
	0x83, 0xbb, 0xa8, 0xf8, 0x09, 0xc4, 0xc9, 0x2d, 0x6d, 0xce, 0x34, 0xd8, 0xf4, 0x42, 0x7a, 0xf1,
	0xf3, 0x4b, 0xa3, 0xe8, 0xf6, 0xf0, 0xfc, 0x96, 0xbf, 0x58, 0x3a, 0xd2, 0x38, 0x00, 0x93, 0xa6,
	0xc6, 0x07, 0x62, 0xda, 0xdc, 0x45, 0x71, 0xa5, 0x33, 0xc9, 0x85, 0xc8, 0xad, 0xae, 0xb2, 0x75,
	0xb6, 0x2d, 0x2f, 0xb9, 0xd5, 0x52, 0x8a, 0x62, 0x54, 0x0e, 0xab, 0x3c, 0x3d, 0x69, 0xcb, 0x95,
	0x28, 0xbb, 0x80, 0x8a, 0x51, 0x1f, 0xb9, 0xfa, 0x4b, 0xf0, 0x3b, 0x66, 0x8d, 0x5e, 0x7f, 0xb4,
	0x78, 0xeb, 0xf7, 0x38, 0x1d, 0x6e, 0x7b, 0x63, 0xb9, 0x8f, 0x6d, 0xd3, 0x91, 0x03, 0x13, 0xed,
	0xd0, 0x63, 0x70, 0x38, 0x31, 0x3e, 0x71, 0x02, 0x43, 0xf5, 0xdc, 0x54, 0x2b, 0x6f, 0xc1, 0x8e,
	0x8c, 0x61, 0x54, 0x03, 0xf8, 0x87, 0x81, 0x8e, 0x02, 0x42, 0x8a, 0x6e, 0xff, 0x53, 0xf0, 0xee,
	0x15, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xf5, 0x31, 0x32, 0xc4, 0x00, 0x00, 0x00,
}
