// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/creating_todo_response.proto

package message // import "github.com/guilhermesteves/go-todo-api/internal/pkg/core/message"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import model "github.com/guilhermesteves/go-todo-api/internal/pkg/core/model"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreatingToDoResponse struct {
	Todo                 *model.ToDo `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreatingToDoResponse) Reset()         { *m = CreatingToDoResponse{} }
func (m *CreatingToDoResponse) String() string { return proto.CompactTextString(m) }
func (*CreatingToDoResponse) ProtoMessage()    {}
func (*CreatingToDoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_creating_todo_response_071f39eb665b9cc8, []int{0}
}
func (m *CreatingToDoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatingToDoResponse.Unmarshal(m, b)
}
func (m *CreatingToDoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatingToDoResponse.Marshal(b, m, deterministic)
}
func (dst *CreatingToDoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatingToDoResponse.Merge(dst, src)
}
func (m *CreatingToDoResponse) XXX_Size() int {
	return xxx_messageInfo_CreatingToDoResponse.Size(m)
}
func (m *CreatingToDoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatingToDoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatingToDoResponse proto.InternalMessageInfo

func (m *CreatingToDoResponse) GetTodo() *model.ToDo {
	if m != nil {
		return m.Todo
	}
	return nil
}

func init() {
	proto.RegisterType((*CreatingToDoResponse)(nil), "CreatingToDoResponse")
}

func init() {
	proto.RegisterFile("message/creating_todo_response.proto", fileDescriptor_creating_todo_response_071f39eb665b9cc8)
}

var fileDescriptor_creating_todo_response_071f39eb665b9cc8 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8e, 0xb1, 0xaa, 0xc2, 0x40,
	0x10, 0x45, 0x09, 0xbc, 0x67, 0x11, 0x1b, 0x11, 0x0b, 0xb5, 0x12, 0xb1, 0xb0, 0x49, 0x06, 0xf5,
	0x07, 0x24, 0xfa, 0x05, 0x62, 0x65, 0x13, 0x36, 0xc9, 0x65, 0xb3, 0x98, 0xdd, 0x59, 0x76, 0x27,
	0x7e, 0xbf, 0x24, 0xa6, 0x3d, 0xe7, 0x0c, 0x73, 0xd3, 0x83, 0x45, 0x8c, 0x4a, 0x83, 0xea, 0x00,
	0x25, 0xc6, 0xe9, 0x52, 0xb8, 0xe1, 0x32, 0x20, 0x7a, 0x76, 0x11, 0xb9, 0x0f, 0x2c, 0xbc, 0x5d,
	0x58, 0x6e, 0xd0, 0xd1, 0xa0, 0x7e, 0x64, 0x7f, 0x4a, 0x57, 0xb7, 0xe9, 0xe2, 0xc9, 0x77, 0x7e,
	0x4c, 0xfd, 0x72, 0x93, 0xfe, 0x0d, 0xd5, 0x3a, 0xd9, 0x25, 0xc7, 0xf9, 0xf9, 0x3f, 0x1f, 0xe5,
	0x88, 0x8a, 0xe2, 0x75, 0xd5, 0x46, 0xda, 0xbe, 0xca, 0x6b, 0xb6, 0xa4, 0x7b, 0xd3, 0xb5, 0x08,
	0x16, 0x51, 0xf0, 0x41, 0x24, 0xcd, 0xd9, 0x50, 0x65, 0xca, 0x1b, 0x32, 0x4e, 0x10, 0x9c, 0xea,
	0xc8, 0xbf, 0x35, 0xd5, 0x1c, 0x40, 0xd3, 0xca, 0x6a, 0x36, 0x7e, 0xbf, 0x7c, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xbe, 0x9b, 0x1d, 0xa3, 0xb7, 0x00, 0x00, 0x00,
}
