// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/creating_todo_request.proto

package message // import "github.com/guilhermesteves/go-todo-api/internal/pkg/core/message"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import model "github.com/guilhermesteves/go-todo-api/internal/pkg/core/model"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreatingToDoResquest struct {
	Todo                 *model.ToDo `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreatingToDoResquest) Reset()         { *m = CreatingToDoResquest{} }
func (m *CreatingToDoResquest) String() string { return proto.CompactTextString(m) }
func (*CreatingToDoResquest) ProtoMessage()    {}
func (*CreatingToDoResquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_creating_todo_request_39034e135751bf8d, []int{0}
}
func (m *CreatingToDoResquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatingToDoResquest.Unmarshal(m, b)
}
func (m *CreatingToDoResquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatingToDoResquest.Marshal(b, m, deterministic)
}
func (dst *CreatingToDoResquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatingToDoResquest.Merge(dst, src)
}
func (m *CreatingToDoResquest) XXX_Size() int {
	return xxx_messageInfo_CreatingToDoResquest.Size(m)
}
func (m *CreatingToDoResquest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatingToDoResquest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatingToDoResquest proto.InternalMessageInfo

func (m *CreatingToDoResquest) GetTodo() *model.ToDo {
	if m != nil {
		return m.Todo
	}
	return nil
}

func init() {
	proto.RegisterType((*CreatingToDoResquest)(nil), "CreatingToDoResquest")
}

func init() {
	proto.RegisterFile("message/creating_todo_request.proto", fileDescriptor_creating_todo_request_39034e135751bf8d)
}

var fileDescriptor_creating_todo_request_39034e135751bf8d = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8e, 0x31, 0x0e, 0x82, 0x40,
	0x10, 0x45, 0x43, 0xa2, 0x16, 0xd8, 0x18, 0x63, 0xa1, 0x56, 0x46, 0x1b, 0x1b, 0x98, 0xa8, 0x17,
	0x30, 0xe8, 0x09, 0x8c, 0x95, 0x0d, 0x59, 0xe0, 0x67, 0xd9, 0xc8, 0x32, 0xb8, 0x3b, 0x78, 0x7e,
	0xc3, 0x4a, 0xfb, 0xde, 0x9b, 0xcc, 0x8f, 0x0f, 0x16, 0xde, 0x2b, 0x0d, 0x2a, 0x1d, 0x94, 0x98,
	0x56, 0xe7, 0xc2, 0x15, 0xe7, 0x0e, 0x9f, 0x1e, 0x5e, 0xd2, 0xce, 0xb1, 0xf0, 0x76, 0x61, 0xb9,
	0x42, 0x43, 0x83, 0xf9, 0x93, 0xfd, 0x29, 0x5e, 0xdd, 0xc6, 0x83, 0x27, 0xdf, 0xf9, 0x01, 0x1f,
	0xfa, 0xe5, 0x26, 0x9e, 0x0c, 0xd5, 0x3a, 0xda, 0x45, 0xc7, 0xf9, 0x79, 0x9a, 0x06, 0x19, 0x50,
	0x96, 0xbd, 0xae, 0xda, 0x48, 0xdd, 0x17, 0x69, 0xc9, 0x96, 0x74, 0x6f, 0x9a, 0x1a, 0xce, 0xc2,
	0x0b, 0xbe, 0xf0, 0xa4, 0x39, 0x19, 0xaa, 0x44, 0x75, 0x86, 0x4c, 0x2b, 0x70, 0xad, 0x6a, 0xa8,
	0x7b, 0x6b, 0x2a, 0xd9, 0x81, 0xc6, 0x91, 0xc5, 0x2c, 0x7c, 0xbf, 0xfc, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xd0, 0x21, 0x9a, 0x04, 0xb6, 0x00, 0x00, 0x00,
}
