// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/deleting_todo_response.proto

package message // import "github.com/guilhermesteves/go-todo-api/internal/pkg/core/message"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeletingToDoResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletingToDoResponse) Reset()         { *m = DeletingToDoResponse{} }
func (m *DeletingToDoResponse) String() string { return proto.CompactTextString(m) }
func (*DeletingToDoResponse) ProtoMessage()    {}
func (*DeletingToDoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_deleting_todo_response_0071e9b76362c13b, []int{0}
}
func (m *DeletingToDoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletingToDoResponse.Unmarshal(m, b)
}
func (m *DeletingToDoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletingToDoResponse.Marshal(b, m, deterministic)
}
func (dst *DeletingToDoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletingToDoResponse.Merge(dst, src)
}
func (m *DeletingToDoResponse) XXX_Size() int {
	return xxx_messageInfo_DeletingToDoResponse.Size(m)
}
func (m *DeletingToDoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletingToDoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletingToDoResponse proto.InternalMessageInfo

func (m *DeletingToDoResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*DeletingToDoResponse)(nil), "DeletingToDoResponse")
}

func init() {
	proto.RegisterFile("message/deleting_todo_response.proto", fileDescriptor_deleting_todo_response_0071e9b76362c13b)
}

var fileDescriptor_deleting_todo_response_0071e9b76362c13b = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xce, 0xb1, 0x0a, 0xc2, 0x30,
	0x14, 0x85, 0x61, 0xba, 0xa8, 0x74, 0x14, 0x87, 0x8e, 0x22, 0x0e, 0x2e, 0xed, 0x15, 0x7c, 0x01,
	0x29, 0x7d, 0x82, 0xe2, 0xe4, 0x52, 0xda, 0xf4, 0x90, 0x06, 0xdb, 0xdc, 0x90, 0x7b, 0xeb, 0xf3,
	0x8b, 0x12, 0xc7, 0xc3, 0x3f, 0x7c, 0x27, 0x3f, 0x2f, 0x10, 0xe9, 0x2d, 0x68, 0xc4, 0x0c, 0x75,
	0xde, 0x76, 0xca, 0x23, 0x77, 0x11, 0x12, 0xd8, 0x0b, 0xaa, 0x10, 0x59, 0xf9, 0x74, 0xcd, 0x0f,
	0x4d, 0xea, 0x0f, 0x6e, 0xb8, 0x4d, 0x75, 0x5f, 0xe4, 0x5b, 0x59, 0x8d, 0x81, 0x48, 0x91, 0x1d,
	0xb3, 0xcb, 0xae, 0xfd, 0xcf, 0xba, 0x7e, 0xde, 0xad, 0xd3, 0x69, 0x1d, 0x2a, 0xc3, 0x0b, 0xd9,
	0xd5, 0xcd, 0x13, 0xe2, 0x02, 0x51, 0xbc, 0x21, 0x64, 0xb9, 0xfc, 0x32, 0x65, 0x1f, 0x1c, 0x39,
	0xaf, 0x88, 0xbe, 0x9f, 0x29, 0xbc, 0x2c, 0x19, 0x8e, 0xa0, 0x74, 0x69, 0xd8, 0xfc, 0xf0, 0xdb,
	0x27, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x87, 0x93, 0x07, 0xa4, 0x00, 0x00, 0x00,
}
