// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/deleting_todo_request.proto

package message // import "github.com/guilhermesteves/go-todo-api/internal/pkg/core/message"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeletingToDoResquest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletingToDoResquest) Reset()         { *m = DeletingToDoResquest{} }
func (m *DeletingToDoResquest) String() string { return proto.CompactTextString(m) }
func (*DeletingToDoResquest) ProtoMessage()    {}
func (*DeletingToDoResquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_deleting_todo_request_e148ff9e7794d3bb, []int{0}
}
func (m *DeletingToDoResquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletingToDoResquest.Unmarshal(m, b)
}
func (m *DeletingToDoResquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletingToDoResquest.Marshal(b, m, deterministic)
}
func (dst *DeletingToDoResquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletingToDoResquest.Merge(dst, src)
}
func (m *DeletingToDoResquest) XXX_Size() int {
	return xxx_messageInfo_DeletingToDoResquest.Size(m)
}
func (m *DeletingToDoResquest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletingToDoResquest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletingToDoResquest proto.InternalMessageInfo

func (m *DeletingToDoResquest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*DeletingToDoResquest)(nil), "DeletingToDoResquest")
}

func init() {
	proto.RegisterFile("message/deleting_todo_request.proto", fileDescriptor_deleting_todo_request_e148ff9e7794d3bb)
}

var fileDescriptor_deleting_todo_request_e148ff9e7794d3bb = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0xce, 0xb1, 0x0a, 0x82, 0x50,
	0x14, 0xc6, 0x71, 0x74, 0x08, 0x72, 0x68, 0x88, 0x86, 0xc6, 0x28, 0x88, 0x16, 0x3d, 0x43, 0x2f,
	0x10, 0xe2, 0x13, 0x48, 0x53, 0x8b, 0xa8, 0xf7, 0xe3, 0x7a, 0x48, 0x3d, 0x76, 0xcf, 0xb1, 0xe7,
	0x8f, 0xc4, 0xf9, 0x07, 0xdf, 0xf7, 0x4f, 0x2e, 0x03, 0x54, 0x6b, 0x0f, 0x72, 0xe8, 0x61, 0x3c,
	0xfa, 0xca, 0xc4, 0x49, 0x15, 0xf0, 0x99, 0xa1, 0x96, 0x4d, 0x41, 0x4c, 0xce, 0xd7, 0xe4, 0x50,
	0xac, 0xfc, 0x94, 0x42, 0x4a, 0xe8, 0xa2, 0xfb, 0x5d, 0x12, 0xb3, 0x3b, 0x46, 0xa7, 0xe8, 0xb6,
	0x2d, 0x63, 0x76, 0x79, 0xfe, 0x7a, 0x78, 0xb6, 0x6e, 0x6e, 0xb2, 0x56, 0x06, 0xf2, 0x33, 0xf7,
	0x1d, 0xc2, 0x00, 0x35, 0x7c, 0xa1, 0xe4, 0x25, 0xfd, 0x6f, 0xa7, 0xf5, 0xc4, 0xc4, 0xa3, 0x21,
	0x8c, 0x75, 0x4f, 0xd3, 0xdb, 0x53, 0x2b, 0x01, 0xb4, 0x76, 0x34, 0x9b, 0xe5, 0xf2, 0xfe, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x6d, 0xa2, 0x5a, 0xd0, 0x99, 0x00, 0x00, 0x00,
}
