// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/listing_todo_response.proto

package message // import "github.com/guilhermesteves/go-todo-api/internal/pkg/core/message"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import model "github.com/guilhermesteves/go-todo-api/internal/pkg/core/model"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListingToDoResponse struct {
	Todos                []*model.ToDo `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListingToDoResponse) Reset()         { *m = ListingToDoResponse{} }
func (m *ListingToDoResponse) String() string { return proto.CompactTextString(m) }
func (*ListingToDoResponse) ProtoMessage()    {}
func (*ListingToDoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_listing_todo_response_d269130c4b18c543, []int{0}
}
func (m *ListingToDoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingToDoResponse.Unmarshal(m, b)
}
func (m *ListingToDoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingToDoResponse.Marshal(b, m, deterministic)
}
func (dst *ListingToDoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingToDoResponse.Merge(dst, src)
}
func (m *ListingToDoResponse) XXX_Size() int {
	return xxx_messageInfo_ListingToDoResponse.Size(m)
}
func (m *ListingToDoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingToDoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListingToDoResponse proto.InternalMessageInfo

func (m *ListingToDoResponse) GetTodos() []*model.ToDo {
	if m != nil {
		return m.Todos
	}
	return nil
}

func init() {
	proto.RegisterType((*ListingToDoResponse)(nil), "ListingToDoResponse")
}

func init() {
	proto.RegisterFile("message/listing_todo_response.proto", fileDescriptor_listing_todo_response_d269130c4b18c543)
}

var fileDescriptor_listing_todo_response_d269130c4b18c543 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8e, 0x3f, 0x0b, 0xc2, 0x30,
	0x10, 0x47, 0x11, 0xa9, 0x43, 0x5d, 0x44, 0x17, 0xd1, 0x45, 0x74, 0x71, 0x69, 0x0f, 0xea, 0x17,
	0x90, 0xe2, 0xe8, 0x24, 0x4e, 0x2e, 0xa5, 0x7f, 0x8e, 0x34, 0x98, 0xe4, 0x42, 0xee, 0xea, 0xe7,
	0x97, 0x36, 0x5d, 0xdf, 0x7b, 0xc7, 0xfd, 0xd2, 0x8b, 0x45, 0xe6, 0x5a, 0x21, 0x18, 0xcd, 0xa2,
	0x9d, 0xaa, 0x84, 0x3a, 0xaa, 0x02, 0xb2, 0x27, 0xc7, 0x98, 0xfb, 0x40, 0x42, 0x87, 0x8d, 0xa5,
	0x0e, 0x0d, 0x8c, 0x2a, 0x92, 0x73, 0x91, 0xee, 0x9e, 0xf1, 0xe0, 0x4d, 0x0f, 0x7a, 0xcd, 0xf9,
	0xf6, 0x98, 0x26, 0x63, 0xc4, 0xfb, 0xc5, 0x69, 0x79, 0x5d, 0x17, 0x49, 0x3e, 0xd9, 0xc8, 0xca,
	0xf2, 0x73, 0x57, 0x5a, 0xfa, 0xa1, 0xc9, 0x5b, 0xb2, 0xa0, 0x06, 0x6d, 0x7a, 0x0c, 0x16, 0x59,
	0xf0, 0x87, 0x0c, 0x8a, 0xb2, 0x31, 0xcb, 0x6a, 0xaf, 0x41, 0x3b, 0xc1, 0xe0, 0x6a, 0x03, 0xfe,
	0xab, 0xa0, 0xa5, 0x80, 0x30, 0xaf, 0x6c, 0x56, 0xd3, 0xfb, 0xdb, 0x3f, 0x00, 0x00, 0xff, 0xff,
	0x45, 0x4a, 0xcd, 0x4e, 0xb7, 0x00, 0x00, 0x00,
}
