// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/loading_todo_request.proto

package message // import "github.com/guilhermesteves/go-todo-api/internal/pkg/core/message"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoadingToDoResquest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadingToDoResquest) Reset()         { *m = LoadingToDoResquest{} }
func (m *LoadingToDoResquest) String() string { return proto.CompactTextString(m) }
func (*LoadingToDoResquest) ProtoMessage()    {}
func (*LoadingToDoResquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_loading_todo_request_d247eb016a064b10, []int{0}
}
func (m *LoadingToDoResquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadingToDoResquest.Unmarshal(m, b)
}
func (m *LoadingToDoResquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadingToDoResquest.Marshal(b, m, deterministic)
}
func (dst *LoadingToDoResquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadingToDoResquest.Merge(dst, src)
}
func (m *LoadingToDoResquest) XXX_Size() int {
	return xxx_messageInfo_LoadingToDoResquest.Size(m)
}
func (m *LoadingToDoResquest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadingToDoResquest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadingToDoResquest proto.InternalMessageInfo

func (m *LoadingToDoResquest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*LoadingToDoResquest)(nil), "LoadingToDoResquest")
}

func init() {
	proto.RegisterFile("message/loading_todo_request.proto", fileDescriptor_loading_todo_request_d247eb016a064b10)
}

var fileDescriptor_loading_todo_request_d247eb016a064b10 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0xce, 0xb1, 0x0b, 0x82, 0x50,
	0x10, 0xc7, 0x71, 0x74, 0x08, 0x72, 0x68, 0xa8, 0xa5, 0x31, 0x84, 0xa0, 0x45, 0x6f, 0xe8, 0x1f,
	0x08, 0x69, 0x6c, 0x92, 0xa6, 0x16, 0x79, 0xfa, 0x8e, 0xf3, 0x48, 0x3d, 0x7b, 0x77, 0xaf, 0xbf,
	0x3f, 0xb2, 0xe6, 0x0f, 0xfc, 0x7e, 0xdf, 0x2c, 0x1f, 0x51, 0xd5, 0x11, 0xc2, 0x20, 0xce, 0xf3,
	0x44, 0x8d, 0x89, 0x97, 0x26, 0xe0, 0x2b, 0xa2, 0x5a, 0x39, 0x07, 0x31, 0xc9, 0x8f, 0xd9, 0xee,
	0xf6, 0xd3, 0xbb, 0x5c, 0xa5, 0x46, 0x5d, 0x70, 0xbb, 0xc9, 0x52, 0xf6, 0xfb, 0xe4, 0x90, 0x9c,
	0xd6, 0x75, 0xca, 0xbe, 0xaa, 0x1e, 0x17, 0x62, 0xeb, 0x63, 0x5b, 0x76, 0x32, 0x02, 0x45, 0x1e,
	0x7a, 0x0c, 0x23, 0xaa, 0xe1, 0x1b, 0x15, 0x48, 0x8a, 0xef, 0x74, 0xe1, 0x66, 0x06, 0x9e, 0x0c,
	0xc3, 0xe4, 0x06, 0x98, 0x9f, 0x04, 0x9d, 0x04, 0x84, 0x7f, 0x45, 0xbb, 0x5a, 0x1e, 0xcf, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x70, 0x0a, 0x79, 0x97, 0x00, 0x00, 0x00,
}
