// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/updating_todo_request.proto

package message // import "github.com/guilhermesteves/go-todo-api/internal/pkg/core/message"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import model "github.com/guilhermesteves/go-todo-api/internal/pkg/core/model"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdatingToDoResquest struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Todo                 *model.ToDo `protobuf:"bytes,2,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdatingToDoResquest) Reset()         { *m = UpdatingToDoResquest{} }
func (m *UpdatingToDoResquest) String() string { return proto.CompactTextString(m) }
func (*UpdatingToDoResquest) ProtoMessage()    {}
func (*UpdatingToDoResquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_updating_todo_request_c3a4bd4cc41f11d6, []int{0}
}
func (m *UpdatingToDoResquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatingToDoResquest.Unmarshal(m, b)
}
func (m *UpdatingToDoResquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatingToDoResquest.Marshal(b, m, deterministic)
}
func (dst *UpdatingToDoResquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatingToDoResquest.Merge(dst, src)
}
func (m *UpdatingToDoResquest) XXX_Size() int {
	return xxx_messageInfo_UpdatingToDoResquest.Size(m)
}
func (m *UpdatingToDoResquest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatingToDoResquest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatingToDoResquest proto.InternalMessageInfo

func (m *UpdatingToDoResquest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdatingToDoResquest) GetTodo() *model.ToDo {
	if m != nil {
		return m.Todo
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdatingToDoResquest)(nil), "UpdatingToDoResquest")
}

func init() {
	proto.RegisterFile("message/updating_todo_request.proto", fileDescriptor_updating_todo_request_c3a4bd4cc41f11d6)
}

var fileDescriptor_updating_todo_request_c3a4bd4cc41f11d6 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8e, 0xcd, 0x6a, 0x83, 0x40,
	0x14, 0x46, 0x51, 0xda, 0x42, 0xa7, 0x50, 0x8a, 0x74, 0x61, 0xbb, 0x92, 0x64, 0xe3, 0x46, 0x2f,
	0x24, 0x2f, 0x90, 0x48, 0x9e, 0x40, 0x92, 0x4d, 0x36, 0x32, 0x3a, 0x97, 0x71, 0x88, 0xe3, 0x9d,
	0xcc, 0x4f, 0x9e, 0x3f, 0x38, 0x71, 0xfb, 0x7d, 0xe7, 0xc0, 0x61, 0x5b, 0x8d, 0xce, 0x71, 0x89,
	0x10, 0x8c, 0xe0, 0x5e, 0xcd, 0xb2, 0xf3, 0x24, 0xa8, 0xb3, 0x78, 0x0f, 0xe8, 0x7c, 0x6d, 0x2c,
	0x79, 0xfa, 0xff, 0xd1, 0x24, 0x70, 0x82, 0xe5, 0x79, 0x2d, 0x9b, 0x23, 0xfb, 0xbd, 0xac, 0xc2,
	0x99, 0x4e, 0xd4, 0xa2, 0x8b, 0x7c, 0xf6, 0xcd, 0x52, 0x25, 0xf2, 0xa4, 0x48, 0xca, 0xcf, 0x36,
	0x55, 0x22, 0xfb, 0x63, 0x6f, 0x8b, 0x95, 0xa7, 0x45, 0x52, 0x7e, 0xed, 0xde, 0xeb, 0x08, 0xc7,
	0xa9, 0x69, 0xae, 0x07, 0xa9, 0xfc, 0x18, 0xfa, 0x7a, 0x20, 0x0d, 0x32, 0xa8, 0x69, 0x44, 0xab,
	0xd1, 0x79, 0x7c, 0xa0, 0x03, 0x49, 0xd5, 0x42, 0x55, 0xdc, 0x28, 0x50, 0xb3, 0x47, 0x3b, 0xf3,
	0x09, 0xcc, 0x4d, 0xc2, 0x40, 0x16, 0x61, 0x8d, 0xee, 0x3f, 0x62, 0xcd, 0xfe, 0x19, 0x00, 0x00,
	0xff, 0xff, 0xfe, 0xce, 0x94, 0xe6, 0xc6, 0x00, 0x00, 0x00,
}
