// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/updating_todo_response.proto

package message // import "github.com/guilhermesteves/go-todo-api/internal/pkg/core/message"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import model "github.com/guilhermesteves/go-todo-api/internal/pkg/core/model"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdatingToDoResponse struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Todo                 *model.ToDo `protobuf:"bytes,2,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdatingToDoResponse) Reset()         { *m = UpdatingToDoResponse{} }
func (m *UpdatingToDoResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatingToDoResponse) ProtoMessage()    {}
func (*UpdatingToDoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_updating_todo_response_19aba71d22466018, []int{0}
}
func (m *UpdatingToDoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatingToDoResponse.Unmarshal(m, b)
}
func (m *UpdatingToDoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatingToDoResponse.Marshal(b, m, deterministic)
}
func (dst *UpdatingToDoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatingToDoResponse.Merge(dst, src)
}
func (m *UpdatingToDoResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatingToDoResponse.Size(m)
}
func (m *UpdatingToDoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatingToDoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatingToDoResponse proto.InternalMessageInfo

func (m *UpdatingToDoResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdatingToDoResponse) GetTodo() *model.ToDo {
	if m != nil {
		return m.Todo
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdatingToDoResponse)(nil), "UpdatingToDoResponse")
}

func init() {
	proto.RegisterFile("message/updating_todo_response.proto", fileDescriptor_updating_todo_response_19aba71d22466018)
}

var fileDescriptor_updating_todo_response_19aba71d22466018 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x3f, 0x6b, 0xc3, 0x30,
	0x10, 0x47, 0x71, 0xe9, 0x3f, 0xd4, 0xa5, 0x98, 0x0e, 0x6e, 0x27, 0x53, 0x3a, 0x78, 0xb1, 0x0f,
	0xda, 0x2f, 0x50, 0x4c, 0xb6, 0x6c, 0x26, 0x59, 0xb2, 0x18, 0x59, 0x3e, 0x64, 0x11, 0x4b, 0x27,
	0x74, 0x52, 0x3e, 0x7f, 0xb0, 0xe3, 0x8c, 0xf7, 0xbb, 0xf7, 0xe0, 0x89, 0x1f, 0x8b, 0xcc, 0x52,
	0x23, 0x24, 0x3f, 0xca, 0x68, 0x9c, 0xee, 0x23, 0x8d, 0xd4, 0x07, 0x64, 0x4f, 0x8e, 0xb1, 0xf1,
	0x81, 0x22, 0x7d, 0xbd, 0x5b, 0x1a, 0x71, 0x86, 0xe5, 0x75, 0x5b, 0xbe, 0xf7, 0xe2, 0xe3, 0xb8,
	0x19, 0x07, 0xda, 0x51, 0xb7, 0xf1, 0x79, 0x21, 0x5e, 0x38, 0x29, 0x85, 0xcc, 0x45, 0x56, 0x66,
	0xd5, 0x6b, 0x77, 0x3f, 0xf3, 0x4f, 0xf1, 0xb8, 0xf8, 0xc5, 0x43, 0x99, 0x55, 0x6f, 0xbf, 0x4f,
	0xcd, 0xaa, 0xad, 0x53, 0xdb, 0x9e, 0xfe, 0xb5, 0x89, 0x53, 0x1a, 0x1a, 0x45, 0x16, 0x74, 0x32,
	0xf3, 0x84, 0xc1, 0x22, 0x47, 0xbc, 0x20, 0x83, 0xa6, 0x7a, 0xa1, 0x6a, 0xe9, 0x0d, 0x18, 0x17,
	0x31, 0x38, 0x39, 0x83, 0x3f, 0x6b, 0x50, 0x14, 0x10, 0xb6, 0xfe, 0xe1, 0x79, 0xed, 0xfa, 0xbb,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x48, 0x83, 0xd7, 0xb2, 0xd1, 0x00, 0x00, 0x00,
}
